In [15]:
import numpy as np
import pandas as pd

def exercise_01():
    a = np.array([2, 3, 4])
    b = np.array([(1.5, 2, 3), (1.5, 2, 3)])
    c = np.arange(15)
    d = np.arange(15).reshape(3, 5)
    e = np.zeros((3, 4))
    f = np.ones((2, 3, 4), dtype=np.int16)
    g = np.eye(3)
    h = np.random.rand(2, 3)
    i = h.max()
    j = h.argmax()
    k = a * 2
    l = b.sum(axis=0)
    m = np.exp(c)

    print("Audsadawut Nakthungtao 66133505", "\nอัษฎาวุฒิ นาคทุ่งเตา 66133505\n", "-"*40)
    print("a:", a, "shape:", a.shape)
    print("b:", b, "shape:", b.shape)
    print("c:", c, "shape:", c.shape)
    print("d:", d, "shape:", d.shape)
    print("e:", e, "shape:", e.shape)
    print("f:", f, "shape:", f.shape)
    print("g:", g, "shape:", g.shape)
    print("h:", h, "shape:", h.shape)
    print("i:", i)
    print("j:", j)
    print("k:", k)
    print("l:", l)
    print("m:", m)

def exercise_02():
    data = {
    "calories": [420, 380, 390],
    "duration": [50, 40, 45]
    }
    df = pd.DataFrame(data)
    print('DataFrame:\n', df, "\n", "-"*40)
    print(df["calories"])
    print(df.describe())
    print(df.loc[0])
    print(df.loc[[0, 1]])

if __name__ == "__main__":
    exercise_01()
    print("\n" + "="*40 + "\n")
   exercise_02()

Audsadawut Nakthungtao 66133505 
อัษฎาวุฒิ นาคทุ่งเตา 66133505
 ----------------------------------------
a: [2 3 4] shape: (3,)
b: [[1.5 2.  3. ]
 [1.5 2.  3. ]] shape: (2, 3)
c: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] shape: (15,)
d: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] shape: (3, 5)
e: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] shape: (3, 4)
f: [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]] shape: (2, 3, 4)
g: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] shape: (3, 3)
h: [[0.91486439 0.3701587  0.01545662]
 [0.92831856 0.42818415 0.96665482]] shape: (2, 3)
i: 0.9666548190436696
j: 5
k: [4 6 8]
l: [3. 4. 6.]
m: [1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04
 1.62754791e+05 4.42413392e+05 1.20260428e+06]


DataFrame:
    calories  duration
0       420        50
1       380        40
2       390        45